import path from 'node:path';
import { openDatabase } from './src/db/driver.js';
const db = await openDatabase(path.resolve('data/quantfolio.db'));
console.log('driver:', db.driverName());
const calA = db.all(`SELECT DISTINCT trade_date FROM daily_quotes WHERE trade_date BETWEEN ? AND ? ORDER BY trade_date`, ['2026-08-05','2026-08-10']).map(r=>r.trade_date);
console.log('calendar [08-05..08-10]:', calA);
const calB = db.all(`SELECT DISTINCT trade_date FROM daily_quotes WHERE trade_date BETWEEN ? AND ? ORDER BY trade_date`, ['2026-08-01','2026-08-10']).map(r=>r.trade_date);
console.log('calendar [08-01..08-10] len:', calB.length, 'first:', calB[0], 'last:', calB[calB.length-1]);
const last = db.get(`SELECT MAX(trade_date) AS d FROM daily_quotes`);
console.log('global MAX trade_date:', last.d);
const cnt = db.get(`SELECT COUNT(*) AS c FROM daily_quotes WHERE trade_date = ?`, ['2026-08-10']);
console.log('rows on 2026-08-10:', cnt.c);
const cntTech = db.get(`SELECT COUNT(*) AS c FROM tech_indicators WHERE trade_date = ?`, ['2026-08-10']);
console.log('tech rows on 2026-08-10:', cntTech.c);
const sample = db.get(`SELECT code, pct_chg FROM daily_quotes WHERE trade_date = ? LIMIT 1`, ['2026-08-10']);
console.log('sample 2026-08-10:', sample);
const tables = db.all(`SELECT name FROM sqlite_master WHERE type='table' AND name IN ('backtests','daily_quotes','tech_indicators','money_flow','auction_data','limit_records','securities')`);
console.log('tables present:', tables.map(t=>t.name));
db.close();
